name: Swift Tests
on:
  push:
  pull_request:
jobs:
  macos:
    # runs-on: macOS-latest
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Build and Test
      #  run: cd ArchiveCore && swift test --enable-code-coverage
        # env:
        #   DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
