name: Xcode Build Tests
on:
  push:
  pull_request:
jobs:
  macos:
    # runs-on: macOS-latest
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Build and Test
      #  run: "xcodebuild test -workspace PDFArchiver.xcworkspace -scheme iOS -destination 'platform=iOS Simulator,name=iPhone 11'"
        # env:
        #   DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
